#********************************************************************
#        配置文件---在这里启用不同环境配置 - yml如何多环境配置不知道
#********************************************************************
preprocessing:
  function-list: # 功能列表
    name: "功能列表"
    group: # 分为三个功能组
      - id: 1
        name: "数值型功能组"
        type: 1
        functions: # 功能组下有多个功能
          - id: 1
            name: "数据清洗"
            children:
              - id: 10
                name: "缺失值处理"
                children:
                  - id: 100
                    name: "均值替换"
                  - id: 101
                    name: "中位数替换"
                  - id: 102
                    name: "众数替换"
                  - id: 104
                    name: "固定值替换"
              - id: 11
                name: "异常值处理"
          - id: 2
            name: "属性变换"
          - id: 3
            name: "特征变换"
          - id: 4
            name: "其他功能"
      - id: 2
        name: "时间型功能组"
        type: 2
      - id: 3
        name: "字符串型功能组"
        type: 3